name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  BUILD_TYPE: Release
  DOTNET_VERSION: 8
  ASSEMBLY_NAME: SourceLand.Qiao

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}.0.x

      - name: Build
        run: dotnet publish -c ${{ env.BUILD_TYPE }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.ASSEMBLY_NAME }}.${{ github.sha }}
          path: src/bin
