name: .NET
on:
  push:
    paths:
      - "**.cs"
  pull_request:
    paths:
      - "**.cs"
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: dotnet build --configuration Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: artifact
          path: D:\a\Qiao\Qiao\src\bin\Release
